//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaShop.Models.PizzaEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public long OrderProductId { get; set; }
        public long OrderId { get; set; }
        public int ProductId { get; set; }
        public int ProductQuantity { get; set; }
        public Nullable<int> ProductSlizes { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductChees { get; set; }
        public string ProductSauce { get; set; }
        public string ProductCrust { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
